In [1]:
import pandas as pd

In [14]:
data_v1 = pd.read_csv('hybrid_rnns_pytorch/data/openSourceRawDataset.csv', index_col=None)
data_v1.head()

,s_id,block,trial_id,action,reward,rt,payout_1,payout_2,payout_3,payout_4
0,268,1.0,0,0.0,0.75,379.0,0.75,0.97,0.26,0.59
1,268,1.0,1,2.0,0.28,212.0,0.74,0.99,0.28,0.53
2,268,1.0,2,1.0,0.93,128.0,0.72,0.93,0.34,0.49
3,268,1.0,3,3.0,0.47,68.0,0.73,0.98,0.22,0.47
4,268,1.0,4,1.0,0.96,272.0,0.65,0.96,0.25,0.55

In [24]:
data_v1.isna().sum()

s_id            0
block           0
trial_id        0
action          0
reward          0
rt          25341
payout_1        0
payout_2        0
payout_3        0
payout_4        0
dtype: int64

In [15]:
data_v1.columns

Index(['s_id', 'block', 'trial_id', 'action', 'reward', 'rt', 'payout_1',
       'payout_2', 'payout_3', 'payout_4'],
      dtype='object')

In [13]:
data_v2 = pd.read_csv('hybrid_rnns_pytorch/data/openSourceRawDataset_v2.csv', index_col=None)
data_v2.head()

/var/folders/24/vn2zpgs12jdb1wkqdz103h1w0000gn/T/ipykernel_37812/3036027379.py:1: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  data_v2 = pd.read_csv('hybrid_rnns_pytorch/data/openSourceRawDataset_v2.csv', index_col=None)

,Age,Sex,Ethnicity simplified,Time taken,block,trial_id,action,reward,rt,missed,payout_0,payout_1,payout_2,payout_3,s_id
0,29,Female,White,1443.0,1.0,0,0.0,75.0,379.0,False,75.0,97.0,26.0,59.0,268
1,29,Female,White,1443.0,1.0,1,2.0,28.0,212.0,False,74.0,99.0,28.0,53.0,268
2,29,Female,White,1443.0,1.0,2,1.0,93.0,128.0,False,72.0,93.0,34.0,49.0,268
3,29,Female,White,1443.0,1.0,3,3.0,47.0,68.0,False,73.0,98.0,22.0,47.0,268
4,29,Female,White,1443.0,1.0,4,1.0,96.0,272.0,False,65.0,96.0,25.0,55.0,268

In [25]:
data_v2[data_v2['missed'] == True]

,Age,Sex,Ethnicity simplified,Time taken,block,trial_id,action,reward,rt,missed,payout_1,payout_2,payout_3,payout_4,s_id
749,51,Female,White,2199.0,2.0,149,NaN,0.0,NaN,True,45.0,58.0,54.0,93.0,528
3132,35,Male,DATA_EXPIRED,1982.0,3.0,132,NaN,0.0,NaN,True,43.0,61.0,58.0,42.0,544
3300,35,Male,White,1765.0,2.0,0,NaN,0.0,NaN,True,4.0,39.0,10.0,40.0,542
3301,35,Male,White,1765.0,2.0,1,NaN,0.0,NaN,True,4.0,38.0,4.0,39.0,542
3302,35,Male,White,1765.0,2.0,2,NaN,0.0,NaN,True,12.0,42.0,4.0,38.0,542
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
619650,64,Female,White,2070.0,4.0,0,NaN,0.0,NaN,True,55.0,57.0,33.0,61.0,556
621150,51,Male,White,2038.0,4.0,0,NaN,0.0,NaN,True,45.0,37.0,84.0,15.0,548
621151,51,Male,White,2038.0,4.0,1,NaN,0.0,NaN,True,48.0,46.0,84.0,13.0,548
621967,22,Male,White,1866.0,4.0,67,NaN,0.0,NaN,True,50.0,41.0,49.0,46.0,375
622246,25,Male,White,1806.0,1.0,46,NaN,0.0,NaN,True,73.0,40.0,56.0,57.0,274

In [16]:
data_v2.columns

Index(['Age', 'Sex', 'Ethnicity simplified', 'Time taken', 'block', 'trial_id',
       'action', 'reward', 'rt', 'missed', 'payout_0', 'payout_1', 'payout_2',
       'payout_3', 's_id'],
      dtype='object')

In [17]:
data_v2.rename(columns={'payout_0': 'payout_1', 'payout_1': 'payout_2',
                        'payout_2': 'payout_3', 'payout_3': 'payout_4'}, inplace=True)

In [18]:
data_v2.columns

Index(['Age', 'Sex', 'Ethnicity simplified', 'Time taken', 'block', 'trial_id',
       'action', 'reward', 'rt', 'missed', 'payout_1', 'payout_2', 'payout_3',
       'payout_4', 's_id'],
      dtype='object')

In [19]:
data_v2_fil = data_v2[list(data_v1.columns)]

In [20]:
data_v2_fil

,s_id,block,trial_id,action,reward,rt,payout_1,payout_2,payout_3,payout_4
0,268,1.0,0,0.0,75.0,379.0,75.0,97.0,26.0,59.0
1,268,1.0,1,2.0,28.0,212.0,74.0,99.0,28.0,53.0
2,268,1.0,2,1.0,93.0,128.0,72.0,93.0,34.0,49.0
3,268,1.0,3,3.0,47.0,68.0,73.0,98.0,22.0,47.0
4,268,1.0,4,1.0,96.0,272.0,65.0,96.0,25.0,55.0
...,...,...,...,...,...,...,...,...,...,...
623695,212,5.0,145,3.0,66.0,326.0,72.0,47.0,27.0,66.0
623696,212,5.0,146,3.0,72.0,470.0,68.0,43.0,36.0,72.0
623697,212,5.0,147,3.0,73.0,532.0,75.0,51.0,37.0,73.0
623698,212,5.0,148,3.0,72.0,665.0,72.0,40.0,42.0,72.0
623699,212,5.0,149,3.0,76.0,526.0,62.0,41.0,41.0,76.0

In [21]:
data_v2_fil.index

RangeIndex(start=0, stop=623700, step=1)

In [23]:
data_v2_fil == data_v1

,s_id,block,trial_id,action,reward,rt,payout_1,payout_2,payout_3,payout_4
0,True,True,True,True,False,True,False,False,False,False
1,True,True,True,True,False,True,False,False,False,False
2,True,True,True,True,False,True,False,False,False,False
3,True,True,True,True,False,True,False,False,False,False
4,True,True,True,True,False,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
623695,True,True,True,True,False,True,False,False,False,False
623696,True,True,True,True,False,True,False,False,False,False
623697,True,True,True,True,False,True,False,False,False,False
623698,True,True,True,True,False,True,False,False,False,False
623699,True,True,True,True,False,True,False,False,False,False